-- COUNTRIES TABLE
insert into countries (id, name) values (1, 'El Salvador');
insert into countries (id, name) values (2, 'Honduras');
insert into countries (id, name) values (3, 'Nicaragua');
insert into countries (id, name) values (4, 'Costa Rica');
insert into countries (id, name) values (5, 'Panamá');
insert into countries (id, name) values (6, 'Belice');
insert into countries (id, name) values (7, 'Guatemala');
insert into countries (id, name) values (8, 'México');
insert into countries (id, name) values (9, 'Estados Unidos');
insert into countries (id, name) values (10, 'Canadá');

-- INSTITUTIONS TABLE
insert into institutions (id, name, country_id) values (1, 'Botsford, Gleichner and Yost', 5);
insert into institutions (id, name, country_id) values (2, 'Donnelly LLC', 8);
insert into institutions (id, name, country_id) values (3, 'Kirlin and Sons', 1);
insert into institutions (id, name, country_id) values (4, 'Fritsch and Sons', 3);
insert into institutions (id, name, country_id) values (5, 'McDermott and Sons', 5);
insert into institutions (id, name, country_id) values (6, 'Cole and Sons', 4);
insert into institutions (id, name, country_id) values (7, 'White LLC', 10);
insert into institutions (id, name, country_id) values (8, 'Schamberger-Mraz', 6);
insert into institutions (id, name, country_id) values (9, 'Tromp, Howe and Smitham', 3);
insert into institutions (id, name, country_id) values (10, 'Reinger, Johnston and Rath', 8);
insert into institutions (id, name, country_id) values (11, 'Roberts Group', 4);
insert into institutions (id, name, country_id) values (12, 'Schmidt-Brown', 8);
insert into institutions (id, name, country_id) values (13, 'Ernser-Romaguera', 5);
insert into institutions (id, name, country_id) values (14, 'Hansen Group', 4);
insert into institutions (id, name, country_id) values (15, 'Conn Group', 6);
insert into institutions (id, name, country_id) values (16, 'Greenfelder LLC', 4);
insert into institutions (id, name, country_id) values (17, 'Larson Inc', 1);
insert into institutions (id, name, country_id) values (18, 'Bailey, Wiegand and Brekke', 6);
insert into institutions (id, name, country_id) values (19, 'Fay Group', 4);
insert into institutions (id, name, country_id) values (20, 'Rogahn, Reichel and Bartoletti', 2);
insert into institutions (id, name, country_id) values (21, 'Hessel LLC', 2);
insert into institutions (id, name, country_id) values (22, 'Conroy, Monahan and Hane', 5);
insert into institutions (id, name, country_id) values (23, 'Gislason-DuBuque', 7);
insert into institutions (id, name, country_id) values (24, 'White, Powlowski and Treutel', 10);
insert into institutions (id, name, country_id) values (25, 'Connelly, Rosenbaum and Bruen', 7);
insert into institutions (id, name, country_id) values (26, 'Berge and Sons', 3);
insert into institutions (id, name, country_id) values (27, 'Wolf-Glover', 9);
insert into institutions (id, name, country_id) values (28, 'Schaden-Wilkinson', 2);
insert into institutions (id, name, country_id) values (29, 'Hettinger Inc', 8);
insert into institutions (id, name, country_id) values (30, 'Greenholt Inc', 10);
insert into institutions (id, name, country_id) values (31, 'Wolff-Pacocha', 6);
insert into institutions (id, name, country_id) values (32, 'Goodwin, Raynor and Klocko', 4);
insert into institutions (id, name, country_id) values (33, 'Towne-Stokes', 7);
insert into institutions (id, name, country_id) values (34, 'Kautzer Inc', 3);
insert into institutions (id, name, country_id) values (35, 'Harber-Conroy', 1);
insert into institutions (id, name, country_id) values (36, 'Predovic-Legros', 2);
insert into institutions (id, name, country_id) values (37, 'Miller-Maggio', 7);
insert into institutions (id, name, country_id) values (38, 'Kulas, Paucek and Muller', 6);
insert into institutions (id, name, country_id) values (39, 'Jast-Casper', 7);
insert into institutions (id, name, country_id) values (40, 'Frami, Krajcik and Friesen', 3);
insert into institutions (id, name, country_id) values (41, 'Stehr-Crona', 5);
insert into institutions (id, name, country_id) values (42, 'O''Kon Inc', 5);
insert into institutions (id, name, country_id) values (43, 'Gusikowski, Champlin and Schmitt', 2);
insert into institutions (id, name, country_id) values (44, 'Konopelski, Beer and Zulauf', 3);
insert into institutions (id, name, country_id) values (45, 'Strosin, Hessel and Crist', 3);
insert into institutions (id, name, country_id) values (46, 'Stracke Group', 9);
insert into institutions (id, name, country_id) values (47, 'Rath Group', 1);
insert into institutions (id, name, country_id) values (48, 'Dare Inc', 1);
insert into institutions (id, name, country_id) values (49, 'Mann, Jaskolski and Satterfield', 10);
insert into institutions (id, name, country_id) values (50, 'Bayer Group', 5);
insert into institutions (id, name, country_id) values (51, 'Rice-Olson', 9);
insert into institutions (id, name, country_id) values (52, 'Rohan, Kirlin and VonRueden', 2);
insert into institutions (id, name, country_id) values (53, 'Yundt Inc', 4);
insert into institutions (id, name, country_id) values (54, 'Johnson, Okuneva and Altenwerth', 4);
insert into institutions (id, name, country_id) values (55, 'Ullrich-Nader', 3);
insert into institutions (id, name, country_id) values (56, 'Boyle Group', 3);
insert into institutions (id, name, country_id) values (57, 'Huels Group', 4);
insert into institutions (id, name, country_id) values (58, 'Bayer Inc', 9);
insert into institutions (id, name, country_id) values (59, 'Cassin-Pacocha', 6);
insert into institutions (id, name, country_id) values (60, 'Bode, Bernhard and Moen', 5);
insert into institutions (id, name, country_id) values (61, 'Grimes-Glover', 8);
insert into institutions (id, name, country_id) values (62, 'Oberbrunner, Ledner and Lueilwitz', 8);
insert into institutions (id, name, country_id) values (63, 'Tremblay-Stamm', 1);
insert into institutions (id, name, country_id) values (64, 'Dickens, Streich and Halvorson', 9);
insert into institutions (id, name, country_id) values (65, 'Brown-White', 8);
insert into institutions (id, name, country_id) values (66, 'Klein, Emard and Carter', 4);
insert into institutions (id, name, country_id) values (67, 'Towne, Collier and Kub', 7);
insert into institutions (id, name, country_id) values (68, 'Bechtelar-Zboncak', 6);
insert into institutions (id, name, country_id) values (69, 'Stehr-Collier', 8);
insert into institutions (id, name, country_id) values (70, 'Hintz Group', 10);
insert into institutions (id, name, country_id) values (71, 'Dickinson, Pacocha and Doyle', 1);
insert into institutions (id, name, country_id) values (72, 'Johnson-Schumm', 10);
insert into institutions (id, name, country_id) values (73, 'Graham LLC', 1);
insert into institutions (id, name, country_id) values (74, 'Leffler, Gutmann and Jacobs', 1);
insert into institutions (id, name, country_id) values (75, 'Pagac, Green and Quigley', 9);
insert into institutions (id, name, country_id) values (76, 'Kilback, Jacobi and Bernier', 7);
insert into institutions (id, name, country_id) values (77, 'Hyatt-Willms', 8);
insert into institutions (id, name, country_id) values (78, 'Ankunding, Schneider and Hyatt', 7);
insert into institutions (id, name, country_id) values (79, 'Kirlin-Yost', 2);
insert into institutions (id, name, country_id) values (80, 'Cronin-Harber', 7);
insert into institutions (id, name, country_id) values (81, 'Streich-Lakin', 3);
insert into institutions (id, name, country_id) values (82, 'Collins, Boyer and Auer', 3);
insert into institutions (id, name, country_id) values (83, 'Bosco, Ullrich and Champlin', 1);
insert into institutions (id, name, country_id) values (84, 'Runolfsson-Quigley', 7);
insert into institutions (id, name, country_id) values (85, 'Wiegand-Abbott', 7);
insert into institutions (id, name, country_id) values (86, 'Kub-Moen', 7);
insert into institutions (id, name, country_id) values (87, 'Becker LLC', 10);
insert into institutions (id, name, country_id) values (88, 'Murphy, O''Connell and Gottlieb', 6);
insert into institutions (id, name, country_id) values (89, 'Witting and Sons', 7);
insert into institutions (id, name, country_id) values (90, 'Legros-Schowalter', 9);
insert into institutions (id, name, country_id) values (91, 'Schumm, Zboncak and Ritchie', 6);
insert into institutions (id, name, country_id) values (92, 'Waelchi, Larson and Kilback', 9);
insert into institutions (id, name, country_id) values (93, 'Schaefer, Rath and Sauer', 7);
insert into institutions (id, name, country_id) values (94, 'Rau and Sons', 9);
insert into institutions (id, name, country_id) values (95, 'Koepp, Lind and Wehner', 8);
insert into institutions (id, name, country_id) values (96, 'Crooks-Towne', 10);
insert into institutions (id, name, country_id) values (97, 'Feil, Cruickshank and Rice', 5);
insert into institutions (id, name, country_id) values (98, 'Kemmer-Cremin', 8);
insert into institutions (id, name, country_id) values (99, 'Cremin-Schumm', 9);
insert into institutions (id, name, country_id) values (100, 'Fadel Group', 2);

-- USERS TABLE
insert into users (id_document, name, surname, email, password) values (1, 'Fairfax', 'Chippendale', 'fairfax@gmail.com', '$2a$10$rPGB4XJ/9Ml7t8qiaD.RDOzIn1OEyUh58C7iSebsg/9T1aFp1mnw2');
insert into users (id_document, name, surname, email, password) values (2, 'Tasha', 'Morfey', 'tasha@gmail.com', '$2a$10$rPGB4XJ/9Ml7t8qiaD.RDOzIn1OEyUh58C7iSebsg/9T1aFp1mnw2');
insert into users (id_document, name, surname, email, password) values (3, 'Lorenzo', 'Ungerechts', 'lerenzo@gmail.com', '$2a$10$rPGB4XJ/9Ml7t8qiaD.RDOzIn1OEyUh58C7iSebsg/9T1aFp1mnw2');

-- VISITS TABLE
insert into visits (id, date, views) values (1, '2021-10-16', 43);
insert into visits (id, date, views) values (2, '2021-10-12', 63);
insert into visits (id, date, views) values (3, '2021-10-10', 37);